[package]
name = "dummy-data-generator"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
publish = false

[dependencies]
clap = { version = "4.0.18", features = ["derive"] }
rand = "0.8.5"
regex = "1.6.0"
